import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "../globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import Header from "@/components/ui/Header"
import { SanityLive } from "@/sanity/lib/live"
import { draftMode } from "next/headers"
import { DisableDraftMode } from "@/components/ui/DisableDraftMode"
import { SetupVisualEditing } from "../SetupVisualEditing"

const geist = Geist({ subsets: ["latin"] })
const geistMono = Geist_Mono({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.className} ${geistMono.className}`}>
        <body>
          {(await draftMode()).isEnabled && <DisableDraftMode />}

          <main>
            <Header />
            {children}
          </main>

          <SanityLive />

          <SetupVisualEditing /> {/* 👈 runs only in browser */}
        </body>
      </html>
    </ClerkProvider>
  )
}
